"""Initial schema.

The table definitions are generated from twin/db/schema.py. Four things are
added by hand because SQLAlchemy cannot express them:

- The TimescaleDB extension and the three hypertables. Where the extension is
  not installed the tables stay ordinary, which is the documented fallback for
  the non-Docker path in docs/technical/RUNNING.md. Ingest throughput drops and
  the interface is unchanged.
- The truth schema. Ground truth lives here so the twin cannot join against it.
  Its role and grants are 0002.
- The predictor scorecard materialised view.

Revision ID: 0001
Revises:
Created: 2026-08-29
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TIMESCALE_TABLES = {
    "event": "1 day",
    "station_state": "1 hour",
    "buffer_state": "1 hour",
}

# The scorecard the floor reads. Recall is not in it and cannot be: a view over
# predictions alone cannot see the events nobody predicted. Recall is computed
# by joining missed_event, which is why that table exists.
SCORECARD_SQL = """
CREATE MATERIALIZED VIEW predictor_scorecard AS
SELECT
  p.predictor,
  p.line_id,
  p.station_id,
  count(*)                                                   AS made,
  count(*) FILTER (WHERE o.result = 'TRUE_POSITIVE')         AS tp,
  count(*) FILTER (WHERE o.result = 'FALSE_POSITIVE')        AS fp,
  count(*) FILTER (WHERE o.result = 'UNSCOREABLE')           AS unscoreable,
  percentile_cont(0.5) WITHIN GROUP (ORDER BY o.lead_time_s) AS median_lead_s
FROM prediction p
JOIN prediction_outcome o USING (prediction_id)
WHERE p.made_at > now() - interval '14 days'
GROUP BY 1, 2, 3
"""


def _timescale_is_available() -> bool:
    """Report whether the TimescaleDB extension can be created here."""
    available = op.get_bind().execute(
        sa.text(
            "SELECT count(*) FROM pg_available_extensions WHERE name = 'timescaledb'"
        )
    )
    return bool(available.scalar_one())


def upgrade() -> None:
    if _timescale_is_available():
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute("CREATE SCHEMA IF NOT EXISTS truth")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buffer_state",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("buffer_id", sa.Text(), nullable=False),
        sa.Column("occupancy", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("trend", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "occupancy >= 0 AND occupancy <= capacity",
            name=op.f("ck_buffer_state_occupancy"),
        ),
        sa.PrimaryKeyConstraint(
            "ts", "line_id", "buffer_id", name=op.f("pk_buffer_state")
        ),
    )
    op.create_index(
        "ix_buffer_state_line_buffer_ts",
        "buffer_state",
        ["line_id", "buffer_id", "ts"],
        unique=False,
    )
    op.create_table(
        "evaluation_run",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("code_version", sa.Text(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("report_path", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_evaluation_run")),
    )
    op.create_index(
        "ix_evaluation_run_scenario_seed",
        "evaluation_run",
        ["scenario_id", "seed"],
        unique=False,
    )
    op.create_table(
        "event",
        sa.Column("ts_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=True),
        sa.Column("unit_id", sa.Text(), nullable=True),
        sa.Column("ts_ingest", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_adapter", sa.Text(), nullable=False),
        sa.Column("quality_flag", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "quality_flag IN ('OK', 'LATE', 'SKEWED', 'ESTIMATED')",
            name=op.f("ck_event_quality_flag"),
        ),
        sa.PrimaryKeyConstraint("ts_source", "event_id", name=op.f("pk_event")),
    )
    op.create_index(
        "ix_event_line_station_ts",
        "event",
        ["line_id", "station_id", "ts_source"],
        unique=False,
    )
    op.create_index(
        "ix_event_type_ts", "event", ["event_type", "ts_source"], unique=False
    )
    op.create_index(
        "ix_event_unit_ts",
        "event",
        ["unit_id", "ts_source"],
        unique=False,
        postgresql_where=sa.text("unit_id IS NOT NULL"),
    )
    op.create_table(
        "line",
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("takt_s", sa.Numeric(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("line_id", name=op.f("pk_line")),
    )
    op.create_table(
        "sensor_catalogue",
        sa.Column("option_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("signal_provided", sa.Text(), nullable=False),
        sa.Column("indicative_cost_usd", sa.Numeric(), nullable=False),
        sa.Column("install_hours", sa.Numeric(), nullable=False),
        sa.Column("requires_window", sa.Boolean(), nullable=False),
        sa.Column(
            "applicable_to", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "confidence_model", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("option_id", name=op.f("pk_sensor_catalogue")),
    )
    op.create_table(
        "station_state",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_unit_id", sa.Text(), nullable=True),
        sa.Column("cycle_time_lo", sa.Numeric(), nullable=True),
        sa.Column("cycle_time_hi", sa.Numeric(), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "provenance <> 'MEASURED' OR cycle_time_lo IS NOT DISTINCT FROM cycle_time_hi",
            name=op.f("ck_station_state_measured_is_a_point"),
        ),
        sa.CheckConstraint(
            "provenance IN ('MEASURED', 'DERIVED', 'INFERRED')",
            name=op.f("ck_station_state_provenance"),
        ),
        sa.CheckConstraint(
            "state IN ('RUNNING', 'BLOCKED', 'STARVED', 'DOWN', 'CHANGEOVER', 'IDLE', 'IDLE_UNKNOWN')",
            name=op.f("ck_station_state_state"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_station_state_confidence"),
        ),
        sa.CheckConstraint(
            "cycle_time_lo IS NULL OR cycle_time_hi IS NULL OR cycle_time_lo <= cycle_time_hi",
            name=op.f("ck_station_state_bounds_ordered"),
        ),
        sa.PrimaryKeyConstraint(
            "ts", "line_id", "station_id", name=op.f("pk_station_state")
        ),
    )
    op.create_index(
        "ix_station_state_line_station_ts",
        "station_state",
        ["line_id", "station_id", "ts"],
        unique=False,
    )
    op.create_table(
        "scenario_injection",
        sa.Column("injection_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.Text(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=True),
        sa.Column("injected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mechanism", sa.Text(), nullable=False),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("injection_id", name=op.f("pk_scenario_injection")),
        schema="truth",
    )
    op.create_table(
        "counterfactual_run",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("made_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seed_state_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "intervention", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "baseline_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "intervention_result",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("replications", sa.Integer(), nullable=False),
        sa.Column("runtime_ms", sa.Integer(), nullable=False),
        sa.Column("degraded", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "saved_as_decision", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("marked_executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_counterfactual_run_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_counterfactual_run")),
    )
    op.create_index(
        "ix_counterfactual_run_line_made",
        "counterfactual_run",
        ["line_id", "made_at"],
        unique=False,
    )
    op.create_table(
        "data_gap",
        sa.Column("gap_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("source_adapter", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("affected_stations", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("events_lost_estimate", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_data_gap_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("gap_id", name=op.f("pk_data_gap")),
    )
    op.create_index(
        "ix_data_gap_line_started", "data_gap", ["line_id", "started_at"], unique=False
    )
    op.create_table(
        "missed_event",
        sa.Column("missed_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predictor", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_missed_event_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("missed_id", name=op.f("pk_missed_event")),
    )
    op.create_index(
        "ix_missed_event_predictor_occurred",
        "missed_event",
        ["predictor", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "prediction",
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("predictor", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=True),
        sa.Column("unit_id", sa.Text(), nullable=True),
        sa.Column("made_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claim", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column("interval_lo", sa.Numeric(), nullable=True),
        sa.Column("interval_hi", sa.Numeric(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inputs_hash", sa.Text(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("degraded", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_prediction_confidence")
        ),
        sa.CheckConstraint(
            "horizon_end >= made_at", name=op.f("ck_prediction_horizon_forward")
        ),
        sa.CheckConstraint(
            "interval_lo IS NULL OR interval_hi IS NULL OR interval_lo <= interval_hi",
            name=op.f("ck_prediction_interval_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_prediction_line_id_line"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("prediction_id", name=op.f("pk_prediction")),
    )
    op.create_index(
        "ix_prediction_horizon_end", "prediction", ["horizon_end"], unique=False
    )
    op.create_index(
        "ix_prediction_predictor_station_made",
        "prediction",
        ["predictor", "station_id", "made_at"],
        unique=False,
    )
    op.create_table(
        "predictor_state",
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("predictor", sa.Text(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "metrics_at_change", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "state IN ('SHADOW', 'ACTIVE', 'UNAVAILABLE')",
            name=op.f("ck_predictor_state_state"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_predictor_state_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("state_id", name=op.f("pk_predictor_state")),
    )
    op.create_index(
        "ix_predictor_state_predictor_station_changed",
        "predictor_state",
        ["predictor", "station_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "source_health",
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("source_adapter", sa.Text(), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("events_last_min", sa.Integer(), server_default="0", nullable=False),
        sa.Column("estimated_skew_s", sa.Numeric(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('LIVE', 'DEGRADED', 'SILENT')",
            name=op.f("ck_source_health_state"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_source_health_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "line_id", "source_adapter", name=op.f("pk_source_health")
        ),
    )
    op.create_table(
        "source_mapping",
        sa.Column("mapping_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("adapter", sa.Text(), nullable=False),
        sa.Column("native_ref", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=True),
        sa.Column("transform", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_source_mapping_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("mapping_id", name=op.f("pk_source_mapping")),
    )
    op.create_index(
        "ix_source_mapping_line_adapter",
        "source_mapping",
        ["line_id", "adapter"],
        unique=False,
    )
    op.create_table(
        "station",
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("transport_to_next_s", sa.Numeric(), nullable=True),
        sa.Column("is_manual", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint("tier IN ('A', 'B', 'C')", name=op.f("ck_station_tier")),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_station_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("line_id", "station_id", name=op.f("pk_station")),
        sa.UniqueConstraint("line_id", "seq", name=op.f("uq_station_line_id_seq")),
    )
    op.create_index("ix_station_line_seq", "station", ["line_id", "seq"], unique=False)
    op.create_table(
        "variant",
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("variant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("nominal_mix_share", sa.Numeric(), nullable=False),
        sa.CheckConstraint(
            "nominal_mix_share >= 0 AND nominal_mix_share <= 1",
            name=op.f("ck_variant_mix_share"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_variant_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("line_id", "variant_id", name=op.f("pk_variant")),
    )
    op.create_table(
        "buffer",
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("buffer_id", sa.Text(), nullable=False),
        sa.Column("after_station_id", sa.Text(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_buffer_capacity")),
        sa.ForeignKeyConstraint(
            ["line_id", "after_station_id"],
            ["station.line_id", "station.station_id"],
            name=op.f("fk_buffer_line_id_after_station_id_station"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_buffer_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("line_id", "buffer_id", name=op.f("pk_buffer")),
    )
    op.create_table(
        "gate",
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("gate_id", sa.Text(), nullable=False),
        sa.Column("after_station_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("catches", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id", "after_station_id"],
            ["station.line_id", "station.station_id"],
            name=op.f("fk_gate_line_id_after_station_id_station"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_gate_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("line_id", "gate_id", name=op.f("pk_gate")),
    )
    op.create_table(
        "prediction_outcome",
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("actual", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("lead_time_s", sa.Numeric(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "result IN ('TRUE_POSITIVE', 'FALSE_POSITIVE', 'TRUE_NEGATIVE', 'FALSE_NEGATIVE', 'UNSCOREABLE')",
            name=op.f("ck_prediction_outcome_result"),
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["prediction.prediction_id"],
            name=op.f("fk_prediction_outcome_prediction_id_prediction"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("prediction_id", name=op.f("pk_prediction_outcome")),
    )
    op.create_index(
        "ix_prediction_outcome_result", "prediction_outcome", ["result"], unique=False
    )
    op.create_table(
        "sensor_recommendation",
        sa.Column("rec_id", sa.UUID(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observability_score", sa.Numeric(), nullable=False),
        sa.Column("criticality_score", sa.Numeric(), nullable=False),
        sa.Column("unknown_description", sa.Text(), nullable=False),
        sa.Column("option_id", sa.Text(), nullable=False),
        sa.Column("confidence_now", sa.Numeric(), nullable=False),
        sa.Column("confidence_projected", sa.Numeric(), nullable=False),
        sa.Column("modelled_value_lo", sa.Numeric(), nullable=False),
        sa.Column("modelled_value_hi", sa.Numeric(), nullable=False),
        sa.Column("next_window", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realised_confidence", sa.Numeric(), nullable=True),
        sa.CheckConstraint(
            "status IN ('OPEN', 'QUEUED', 'INSTALLED', 'DECLINED')",
            name=op.f("ck_sensor_recommendation_status"),
        ),
        sa.CheckConstraint(
            "modelled_value_lo <= modelled_value_hi",
            name=op.f("ck_sensor_recommendation_value_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id", "station_id"],
            ["station.line_id", "station.station_id"],
            name=op.f("fk_sensor_recommendation_line_id_station_id_station"),
        ),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["sensor_catalogue.option_id"],
            name=op.f("fk_sensor_recommendation_option_id_sensor_catalogue"),
        ),
        sa.PrimaryKeyConstraint("rec_id", name=op.f("pk_sensor_recommendation")),
    )
    op.create_index(
        "ix_sensor_recommendation_line_generated",
        "sensor_recommendation",
        ["line_id", "generated_at"],
        unique=False,
    )
    op.create_table(
        "station_distribution",
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=False),
        sa.Column("variant_id", sa.Text(), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("median", sa.Numeric(), nullable=False),
        sa.Column("mad", sa.Numeric(), nullable=False),
        sa.Column("p05", sa.Numeric(), nullable=False),
        sa.Column("p95", sa.Numeric(), nullable=False),
        sa.Column("empirical", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fit_residual", sa.Numeric(), nullable=True),
        sa.CheckConstraint("n >= 0", name=op.f("ck_station_distribution_sample_count")),
        sa.ForeignKeyConstraint(
            ["line_id", "station_id"],
            ["station.line_id", "station.station_id"],
            name=op.f("fk_station_distribution_line_id_station_id_station"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id", "variant_id"],
            ["variant.line_id", "variant.variant_id"],
            name=op.f("fk_station_distribution_line_id_variant_id_variant"),
        ),
        sa.PrimaryKeyConstraint(
            "line_id",
            "station_id",
            "variant_id",
            "window_end",
            name=op.f("pk_station_distribution"),
        ),
    )
    op.create_table(
        "unit",
        sa.Column("unit_id", sa.Text(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("variant_id", sa.Text(), nullable=False),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_station_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "status IN ('IN_PROCESS', 'COMPLETED', 'REWORK', 'HELD', 'SCRAPPED')",
            name=op.f("ck_unit_status"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id", "variant_id"],
            ["variant.line_id", "variant.variant_id"],
            name=op.f("fk_unit_line_id_variant_id_variant"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.line_id"],
            name=op.f("fk_unit_line_id_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("unit_id", name=op.f("pk_unit")),
    )
    op.create_index(
        "ix_unit_line_entered", "unit", ["line_id", "entered_at"], unique=False
    )
    op.create_table(
        "unit_visit",
        sa.Column("visit_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.Text(), nullable=False),
        sa.Column("line_id", sa.Text(), nullable=False),
        sa.Column("station_id", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("departed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dwell_s", sa.Numeric(), nullable=True),
        sa.Column("cycle_lo", sa.Numeric(), nullable=True),
        sa.Column("cycle_hi", sa.Numeric(), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=False),
        sa.Column("station_state_during", sa.Text(), nullable=True),
        sa.Column("blocked_s", sa.Numeric(), nullable=True),
        sa.Column("starved_s", sa.Numeric(), nullable=True),
        sa.Column(
            "process_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "process_residuals", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("part_lots", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("operator_group", sa.Text(), nullable=True),
        sa.Column("shift_id", sa.Text(), nullable=True),
        sa.Column("env", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "provenance <> 'MEASURED' OR cycle_lo IS NOT DISTINCT FROM cycle_hi",
            name=op.f("ck_unit_visit_measured_is_a_point"),
        ),
        sa.CheckConstraint(
            "provenance IN ('MEASURED', 'DERIVED', 'INFERRED')",
            name=op.f("ck_unit_visit_provenance"),
        ),
        sa.CheckConstraint(
            "cycle_lo IS NULL OR cycle_hi IS NULL OR cycle_lo <= cycle_hi",
            name=op.f("ck_unit_visit_bounds_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["line_id", "station_id"],
            ["station.line_id", "station.station_id"],
            name=op.f("fk_unit_visit_line_id_station_id_station"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.unit_id"],
            name=op.f("fk_unit_visit_unit_id_unit"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("visit_id", name=op.f("pk_unit_visit")),
        sa.UniqueConstraint("unit_id", "seq", name=op.f("uq_unit_visit_unit_id_seq")),
    )
    op.create_index(
        "ix_unit_visit_part_lots",
        "unit_visit",
        ["part_lots"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_unit_visit_station_arrived",
        "unit_visit",
        ["station_id", "arrived_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    if _timescale_is_available():
        for table, chunk in TIMESCALE_TABLES.items():
            op.execute(
                sa.text(
                    "SELECT create_hypertable("
                    ":table, :column, "
                    "chunk_time_interval => CAST(:chunk AS interval), "
                    "migrate_data => true)"
                ).bindparams(
                    table=table,
                    column="ts_source" if table == "event" else "ts",
                    chunk=chunk,
                )
            )

    op.execute(SCORECARD_SQL)
    # A unique index lets the view refresh concurrently, so a cycle refresh does
    # not lock the scorecard the floor is reading. station_id is null for
    # line-level predictors, and two null station ids are the same row here.
    op.execute(
        "CREATE UNIQUE INDEX ix_predictor_scorecard_key "
        "ON predictor_scorecard (predictor, line_id, station_id) NULLS NOT DISTINCT"
    )


def downgrade() -> None:
    op.execute("DROP MATERIALIZED VIEW IF EXISTS predictor_scorecard")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_unit_visit_station_arrived", table_name="unit_visit")
    op.drop_index(
        "ix_unit_visit_part_lots", table_name="unit_visit", postgresql_using="gin"
    )
    op.drop_table("unit_visit")
    op.drop_index("ix_unit_line_entered", table_name="unit")
    op.drop_table("unit")
    op.drop_table("station_distribution")
    op.drop_index(
        "ix_sensor_recommendation_line_generated", table_name="sensor_recommendation"
    )
    op.drop_table("sensor_recommendation")
    op.drop_index("ix_prediction_outcome_result", table_name="prediction_outcome")
    op.drop_table("prediction_outcome")
    op.drop_table("gate")
    op.drop_table("buffer")
    op.drop_table("variant")
    op.drop_index("ix_station_line_seq", table_name="station")
    op.drop_table("station")
    op.drop_index("ix_source_mapping_line_adapter", table_name="source_mapping")
    op.drop_table("source_mapping")
    op.drop_table("source_health")
    op.drop_index(
        "ix_predictor_state_predictor_station_changed", table_name="predictor_state"
    )
    op.drop_table("predictor_state")
    op.drop_index("ix_prediction_predictor_station_made", table_name="prediction")
    op.drop_index("ix_prediction_horizon_end", table_name="prediction")
    op.drop_table("prediction")
    op.drop_index("ix_missed_event_predictor_occurred", table_name="missed_event")
    op.drop_table("missed_event")
    op.drop_index("ix_data_gap_line_started", table_name="data_gap")
    op.drop_table("data_gap")
    op.drop_index("ix_counterfactual_run_line_made", table_name="counterfactual_run")
    op.drop_table("counterfactual_run")
    op.drop_table("scenario_injection", schema="truth")
    op.drop_index("ix_station_state_line_station_ts", table_name="station_state")
    op.drop_table("station_state")
    op.drop_table("sensor_catalogue")
    op.drop_table("line")
    op.drop_index(
        "ix_event_unit_ts",
        table_name="event",
        postgresql_where=sa.text("unit_id IS NOT NULL"),
    )
    op.drop_index("ix_event_type_ts", table_name="event")
    op.drop_index("ix_event_line_station_ts", table_name="event")
    op.drop_table("event")
    op.drop_index("ix_evaluation_run_scenario_seed", table_name="evaluation_run")
    op.drop_table("evaluation_run")
    op.drop_index("ix_buffer_state_line_buffer_ts", table_name="buffer_state")
    op.drop_table("buffer_state")
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS truth CASCADE")
